<?php

namespace App\Controller\Admin;

use App\Entity\Invoice;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CurrencyField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\MoneyField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class InvoiceCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Invoice::class;
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $entityInstance->getPrice();
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $entityInstance->getPrice();
        parent::updateEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        if (Crud::PAGE_INDEX === $pageName) {
            yield TextField::new('billingPeriod', 'Tiempo de pago');
            yield DateField::new('paymentAt', 'Fecha de presupuesto');
            yield TextField::new('paymentMethod', 'Método de pago');
            yield NumberField::new('discount', 'Descuento');
            yield AssociationField::new('client', 'Cliente');
            yield NumberField::new('price', 'Precio total');
        }

        if (Crud::PAGE_NEW === $pageName || Crud::PAGE_EDIT === $pageName) {
            yield TextField::new('billingPeriod', 'Tiempo de pago');
            yield DateField::new('paymentAt', 'Fecha de presupuesto');
            yield TextField::new('paymentMethod', 'Método de pago');
            yield NumberField::new('discount', 'Descuento');
            yield BooleanField::new('isPayed','Pagado');
            yield AssociationField::new('client', 'Cliente');
            yield AssociationField::new('workMades','Trabajos realizados');
        }

        if (Crud::PAGE_DETAIL === $pageName) {
            yield TextField::new('billingPeriod', 'Tiempo de pago');
            yield DateField::new('paymentAt', 'Fecha de presupuesto');
            yield TextField::new('paymentMethod', 'Método de pago');
            yield NumberField::new('discount', 'Descuento');
            yield BooleanField::new('isPayed','Pagado');
            yield AssociationField::new('client', 'Cliente');
        }
    }

}
